config/routes.rb
Rails.application.routes.draw do

  get 'materials/new'

  get 'materials/edit'

  root 'pages#home'

  resources :pages, only: [] do
    collection do
      get 'home'
      get 'about'
      get 'contract'
    end
  end

  resources :blogs

  resources :users do
    collection do
      get 'login'
      post 'auth'
      delete 'logout'
    end
  end

  resources :products do
    resources :materials
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new
      if user.role == 'admin'
        can :manage, :all
      else
        can :read, Product
      end
    #
    # here are :read, :create, :update and :destroy.
    #
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    #
    #   can :update, Article, :published => true
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  validates :title, :image, :content, :content_short, presence: true
end

app/models/material.rb
class Material < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :product

  validates_presence_of :product_id
  validates_presence_of :profile
  validates_presence_of :image
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :materials, dependent: :destroy
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base

  validates_presence_of :username
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :password
  validates_length_of :password, minimum: 6


  enum role: [:admin, :common]
  before_save :password_digest, :email_downcase

private
  def password_digest
    self.password = User.auth_password(password)
  end

  def email_downcase
    self.email = email.downcase
  end

  def self.auth_password(password)
    Digest::SHA1.hexdigest('skin-care-key-rudy' + password)
  end

  def self.auth(params)
    User.where(email: params[:email].downcase,
               password: auth_password(params[:password])).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.where(id: session[:id]).first unless session[:id].nil?
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find_by(id: params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find_by(id: params[:id])
  end

  def update
    @blog = Blog.find_by(id: params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find_by(id: params[:id])
  end

private

  def blog_params
    params.require(:blog).permit(:title, :image, :content, :content_short)
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def new
    @product = Product.find_by(id: params[:product_id])
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)
    if @material.save
     redirect_to product_path(@material.product.id)
    else
      @product = Product.find_by(id: params[:product_id])
      render :new
    end
  end

  def edit
    @product = Product.find_by(id: params[:product_id])
    @material = Material.find_by(id: params[:id])
  end

  def update
    @product = Product.find_by(id: params[:product_id])
    @material = Material.find_by(id: params[:id])

    if @material.update_attributes(material_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @material = Material.find_by(id: params[:id])
    @material.destroy
    @product = Product.find_by(id: params[:product_id])
    redirect_to @product
  end

private
  def material_params
    params.require(:material).permit(:product_id, :image, :profile)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end

  def about
  end

  def contract
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # load_and_authorize_resource param_method: :product_params

  def index
    @products = Product.all
  end

  def show
    # @product = Product.where(id: params[:id]).first
    # @materials = @product.materials
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit
    @product = Product.where(id: params[:id]).first
  end

  def update
    @product = Product.where(id: params[:id]).first
    if @product.update_attributes(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    product = Product.where(id: params[:id]).first
    product.destroy if product

    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :title, :price, :profile, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    @user = User.new
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def auth
    if user = User.auth(params[:user])
      session[:id] = user.id
      hashids = Hashids.new(user.email)
      redirect_to user_path(hashids.encode(user.id))
    else
      @user = User.new(user_params)
      render 'login'
    end
  end

  def show
    @user = current_user

    redirect_to root_path if @user.nil?
  end

  def edit
    @user = current_user

    redirect_to root_path if @user.nil?
  end

  def update
    @user = current_user
    if @user && @user.update_attributes(user_update_params)
      hashids = Hashids.new(@user.email)
      redirect_to user_path(hashids.encode(@user.id))
    else
      render 'edit'
    end
  end

private
  def user_params
    params.require(:user).permit(:email, :password)
  end

  def user_update_params
    params.require(:user).permit(:email, :password, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def hashids(base, key)
    Hashids.new(base).encode(key)
  end

  def is_active?(num)
    actions = ['home', 'products', 'blogs', 'about', 'contract']
    return 'active' if actions[num] == controller_name
    return 'active' if actions[num] == action_name
  end
end

app/views/blogs/_form.html.erb
<ul>
<%= form_for @blog do |f| %>

  <li><%= f.text_field :title, placeholder: '博客标题', class: 'blog-title' %>
  <li>
  <div style='margin-top: 10px'>
  <p> 上传blog 简短展示的图片（已经存在的无需在上传） <%= f.file_field :image %> </p>
</div>
  <li>
  <p> 下面书写blog内容
  <%= f.kindeditor :content%>
  <li>
  <p> 下面书写简短展示时候的blog内容 </p>
  <%= f.text_area :content_short, class: 'blog-short' %>
  <div>
    <%= f.submit '创建blog', class: 'btn btn-primary'%>
  </div>
<% end %>
</ul>
<div style='margin-bottom:10px'></div>

app/views/blogs/edit.html.erb
<div class="container" style="margin-top:60px">
  <%= render 'form' %>
</div>

app/views/blogs/index.html.erb
<div class="container"  style="margin-top:55px;">
 <div class="blog_holder masonry masonry_infinite_scroll" id='my-blog' style="position: relative; height: 3107px; opacity: 1;">
  <article id="post-5" class="my-article post-5 post type-post status-publish format-standard has-post-thumbnail hentry category-design tag-analysis tag-articles tag-business tag-opportunities" style="margin: 5px;">
   <div class="post_image">
    <a href="#"><img src="http://demo.qodeinteractive.com/bridge37/wp-content/uploads/2013/10/b-inteligent-transitions-in-ux-design.jpg" /></a>
   </div>
   <div class="post_text">
    <div class="post_text_inner">
     <h5><a href="http://demo.qodeinteractive.com/bridge37/inteligent-transitions-in-ux-design/" target="_self" title="Transitions In UX Design">Transitions In UX Design</a></h5>
     <p class="post_excerpt">The term minimalism is also used to describe a trend in design and architecture where in the subject is reduced to its necessary...</p>
     <div class="post_info">
      <span class="time">04 October, 2013</span>
     </div>
    </div>
   </div>
  </article>
  <article id="post-5" class="my-article post-5 post type-post status-publish format-standard has-post-thumbnail hentry category-design tag-analysis tag-articles tag-business tag-opportunities" style="margin: 5px;">
   <div class="post_image">
    <a href="#"><img src="http://demo.qodeinteractive.com/bridge37/wp-content/uploads/2013/10/b-inteligent-transitions-in-ux-design.jpg" /></a>
   </div>
   <div class="post_text">
    <div class="post_text_inner">
     <h5><a href="http://demo.qodeinteractive.com/bridge37/inteligent-transitions-in-ux-design/" target="_self" title="Transitions In UX Design">Transitions In UX Design</a></h5>
     <p class="post_excerpt">The term minimalism is also used to describe a trend in design and architecture where in the subject is reduced to its necessary...</p>
     <div class="post_info">
      <span class="time">04 October, 2013</span>
     </div>
    </div>
   </div>
  </article>
  <article id="post-5" class="my-article post-5 post type-post status-publish format-standard has-post-thumbnail hentry category-design tag-analysis tag-articles tag-business tag-opportunities" style="margin: 5px;">
   <div class="post_image">
    <a href="#"><img src="http://demo.qodeinteractive.com/bridge37/wp-content/uploads/2013/10/b-inteligent-transitions-in-ux-design.jpg" /></a>
   </div>
   <div class="post_text">
    <div class="post_text_inner">
     <h5><a href="http://demo.qodeinteractive.com/bridge37/inteligent-transitions-in-ux-design/" target="_self" title="Transitions In UX Design">Transitions In UX Design</a></h5>
     <p class="post_excerpt">The term minimalism is also used to describe a trend in design and architecture where in the subject is reduced to its necessary...</p>
     <div class="post_info">
      <span class="time">04 October, 2013</span>
     </div>
    </div>
   </div>
  </article>
  <article id="post-5" class="my-article post-5 post type-post status-publish format-standard has-post-thumbnail hentry category-design tag-analysis tag-articles tag-business tag-opportunities" style="margin: 5px;">
   <div class="post_image">
    <a href="#"><img src="http://demo.qodeinteractive.com/bridge37/wp-content/uploads/2013/10/b-inteligent-transitions-in-ux-design.jpg" /></a>
   </div>
   <div class="post_text">
    <div class="post_text_inner">
     <h5><a href="http://demo.qodeinteractive.com/bridge37/inteligent-transitions-in-ux-design/" target="_self" title="Transitions In UX Design">Transitions In UX Design</a></h5>
     <p class="post_excerpt">The term minimalism is also used to describe a trend in design and architecture where in the subject is reduced to its necessary...</p>
     <div class="post_info">
      <span class="time">04 October, 2013</span>
     </div>
    </div>
   </div>
  </article>
  <article id="post-5" class="my-article post-5 post type-post status-publish format-standard has-post-thumbnail hentry category-design tag-analysis tag-articles tag-business tag-opportunities" style="margin: 5px;">
   <div class="post_image">
    <a href="#"><img src="http://demo.qodeinteractive.com/bridge37/wp-content/uploads/2013/10/b-inteligent-transitions-in-ux-design.jpg" /></a>
   </div>
   <div class="post_text">
    <div class="post_text_inner">
     <h5><a href="http://demo.qodeinteractive.com/bridge37/inteligent-transitions-in-ux-design/" target="_self" title="Transitions In UX Design">Transitions In UX Design</a></h5>
     <p class="post_excerpt">The term minimalism is also used to describe a trend in design and architecture where in the subject is reduced to its necessary...</p>
     <div class="post_info">
      <span class="time">04 October, 2013</span>
     </div>
    </div>
   </div>
  </article>
 </div>

</div>

app/views/blogs/new.html.erb
<div class="container" style="margin-top:60px">
  <%= render 'form' %>
</div>

app/views/blogs/show.html.erb
<div class="container" style='margin-top:60px'>
  <%= raw @blog.content %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">

  <head>
      <meta charset="UTF-8" />
      <title>
          GAIA | 护肤精品
      </title>

      <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">

      <link rel="shortcut icon" type="image/x-icon" href="http://demo.qodeinteractive.com/bridge79/wp-content/themes/bridge/img/favicon.ico">
      <link rel="apple-touch-icon" href="http://demo.qodeinteractive.com/bridge79/wp-content/themes/bridge/img/favicon.ico"
      />

      <link href="http://vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
      <script src="http://vjs.zencdn.net/4.11/video.js"></script>

      <style type="text/css">
        img.wp-smiley,
        img.emoji {
          display: inline !important;
          border: none !important;
          box-shadow: none !important;
          height: 1em !important;
          width: 1em !important;
          margin: 0 .07em !important;
          vertical-align: -0.1em !important;
          background: none !important;
          padding: 0 !important;
        }
      </style>
    <!-- Google Analytics start -->
    <script>
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-50398491-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    <!-- Google Analytics end -->

      <%= stylesheet_link_tag 'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
      <!--[if gte IE 9]>
          <style type="text/css">
              .gradient { filter: none; }
          </style>
      <![endif]-->


      <!--[if IE 8]>
          <link rel="stylesheet" type="text/css" href="http://demo.qodeinteractive.com/bridge79/wp-content/plugins/js_composer/assets/css/vc-ie8.css"
          media="screen">
      <![endif]-->
  </head>

  <body class="home page page-id-15252 page-template page-template-full_width page-template-full_width-php ajax_fade page_not_loaded  qode-title-hidden paspartu_enabled columns-3 qode-theme-ver-7.0 wpb-js-composer js-comp-ver-4.4.4 vc_responsive">
    <div class="ajax_loader">
      <div class="ajax_loader_1">
          <div class="cube">
          </div>
      </div>
    </div>
    <div class="wrapper">
        <div class="wrapper_inner">
          <%= render '/shared/header' %>
          <div class="blank">
            <%= yield %>
          </div>
          <%= render '/shared/footer' %>
        </div>
    </div>


  </body>

</html>

app/views/materials/_form.html.slim
= form_for [@product, @material] do |f|
  = f.hidden_field 'product_id', value: @product.id
  = f.text_area 'profile', placeholder: '原材料介绍'
  = f.file_field 'image', placeholder: '图片'

  = f.submit button_value

app/views/materials/edit.html.slim
= render partial: 'form', locals: {button_value: '更新'}

app/views/materials/new.html.slim
= render partial: 'form', locals: {button_value: '创建'}

app/views/pages/about.html.slim
section
  .container.content-box
    li 我们是谁
    li 我们叫什么

app/views/pages/blog.html.erb
<html>
 <head></head>
 <body>
  <div class="paspartu_outer  disable_top_paspartu paspartu_on_bottom_fixed">
   <div class="paspartu_left"></div>
   <div class="paspartu_right"></div>
   <div class="paspartu_bottom" style="height: 38px;"></div>
   <div class="paspartu_inner">
    <div class="content content_top_margin_none" style="padding-top: 10px; min-height: auto;">
     <div class="content_inner  " style="position: relative; visibility: visible; display: block;">
      <div class="container">
       <div class="container_inner default_template_holder">
        <div class="blog_holder blog_large_image_simple">

         <article id="post-38" class="post-38 post type-post status-publish format-video has-post-thumbnail hentry category-art tag-art tag-culture tag-events tag-video post_format-post-format-video">
          <div class="post_content_holder my-post">
           <div class="post_text">
            <div class="post_text_inner my-text">
             <div class="minimalist_date">
              October 4, 2013
             </div>
             <h2><a href="http://demo.qodeinteractive.com/bridge79/supernatural-fx-showreel/" title="Supernatural FX Showreel">Supernatural FX Showreel</a></h2>
             <div class="separator small center"></div>
             <p class="post_excerpt">The term minimalism is also used to describe a trend in design and architecture where in the subject is reduced to its necessary elements. Minimalist design has been highly influenced by Japanese traditional design and architecture. In addition, the work of De Stijl artists is a major source of reference...</p>
            </div>
           </div>
          </div>
         </article>
         <article id="post-38" class="post-38 post type-post status-publish format-video has-post-thumbnail hentry category-art tag-art tag-culture tag-events tag-video post_format-post-format-video">
          <div class="post_content_holder my-post">
           <div class="post_text">
            <div class="post_text_inner my-text">
             <div class="minimalist_date">
              October 4, 2013
             </div>
             <h2><a href="http://demo.qodeinteractive.com/bridge79/supernatural-fx-showreel/" title="Supernatural FX Showreel">Supernatural FX Showreel</a></h2>
             <div class="separator small center"></div>
             <p class="post_excerpt">The term minimalism is also used to describe a trend in design and architecture where in the subject is reduced to its necessary elements. Minimalist design has been highly influenced by Japanese traditional design and architecture. In addition, the work of De Stijl artists is a major source of reference...</p>
            </div>
           </div>
          </div>
         </article>
         <article id="post-38" class="post-38 post type-post status-publish format-video has-post-thumbnail hentry category-art tag-art tag-culture tag-events tag-video post_format-post-format-video">
          <div class="post_content_holder my-post">
           <div class="post_text">
            <div class="post_text_inner my-text">
             <div class="minimalist_date">
              October 4, 2013
             </div>
             <h2><a href="http://demo.qodeinteractive.com/bridge79/supernatural-fx-showreel/" title="Supernatural FX Showreel">Supernatural FX Showreel</a></h2>
             <div class="separator small center"></div>
             <p class="post_excerpt">The term minimalism is also used to describe a trend in design and architecture where in the subject is reduced to its necessary elements. Minimalist design has been highly influenced by Japanese traditional design and architecture. In addition, the work of De Stijl artists is a major source of reference...</p>
            </div>
           </div>
          </div>
         </article>
         <div class="pagination">
         此处为排序页
         </div>
        </div>
       </div>
      </div>
      <div class="content_bottom">
      </div>
     </div>
    </div>
   </div>
   <!-- paspartu_inner close div -->
  </div>
  <!-- paspartu_outer close div -->

  <%= form_for Product.new do |f| %>
       <%= f.kindeditor :profile %>
  <% end %>

app/views/pages/contract.html.erb
  <div class="paspartu_inner">
   <div class="content content_top_margin_none" style="min-height: 23px; padding-top: 120px;">
    <div class="meta">
    </div>
    <div class="content_inner  ">
     <div class="full_width">
      <div class="full_width_inner">
       <div class="vc_row wpb_row section vc_row-fluid grid_section" style=" padding-top:0px; padding-bottom:14px; text-align:center;">
        <div class=" section_inner clearfix">
         <div class="section_inner_margin clearfix">
          <div class="vc_col-sm-10 vc_col-lg-offset-2 vc_col-lg-8 vc_col-md-offset-2 vc_col-md-8 vc_col-sm-offset-1 vc_col-xs-offset-1 vc_col-xs-10 wpb_column vc_column_container ">
           <div class="wpb_wrapper">
            <div class="wpb_text_column wpb_content_element ">
             <div class="wpb_wrapper">
              <h3>For further information</h3>
             </div>
            </div>
            <div class="separator  transparent center  " style="margin-top: 20px;margin-bottom: 0px;"></div>
            <div class="wpb_text_column wpb_content_element ">
             <div class="wpb_wrapper">
              <h2>Please Contact Us</h2>
             </div>
            </div>
            <div class="separator  small center  " style=""></div>
           </div>
          </div>
         </div>
        </div>
       </div>
       <div class="vc_row wpb_row section vc_row-fluid grid_section" style=" padding-bottom:80px; text-align:left;">
        <div class=" section_inner clearfix">
         <div class="section_inner_margin clearfix">
          <div class="vc_col-sm-12 wpb_column vc_column_container ">
           <div class="wpb_wrapper">
            <div role="form" class="wpcf7" id="wpcf7-f15337-p15334-o1" lang="en-US" dir="ltr">
             <div class="screen-reader-response"></div>
             <form name="" action="/bridge79/contact-us/#wpcf7-f15337-p15334-o1" method="post" class="wpcf7-form cf7_custom_style_1" novalidate="novalidate">
              <div style="display: none;">
               <input type="hidden" name="_wpcf7" value="15337" />
               <input type="hidden" name="_wpcf7_version" value="4.1.2" />
               <input type="hidden" name="_wpcf7_locale" value="en_US" />
               <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f15337-p15334-o1" />
               <input type="hidden" name="_wpnonce" value="27e9b417d6" />
              </div>
              <div class="three_columns clearfix">
               <div class="column1">
                <div class="column_inner">
                 <span class="wpcf7-form-control-wrap first-name"><input type="text" name="first-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="First Name" /></span>
                </div>
               </div>
               <div class="column2">
                <div class="column_inner">
                 <span class="wpcf7-form-control-wrap last-name"><input type="text" name="last-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Last Name" /></span>
                </div>
               </div>
               <div class="column3">
                <div class="column_inner">
                 <span class="wpcf7-form-control-wrap email"><input type="text" name="email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Email" /></span>
                </div>
               </div>
              </div>
              <p><span class="wpcf7-form-control-wrap message"><textarea name="message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Message"></textarea></span></p>
              <p style="text-align: center;"><input type="submit" value="Contact Us" class="wpcf7-form-control wpcf7-submit" /><img class="ajax-loader" src="http://demo.qodeinteractive.com/bridge79/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;" /></p>
              <div class="wpcf7-response-output wpcf7-display-none"></div>
             </form>
            </div>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
     <div class="content_bottom">
     </div>
    </div>
   </div>
  </div>
 </body>
</html>

app/views/products/_form.html.slim
div
  = form_for @product do |f|
    li= f.text_field 'name', placeholder: '产品名字'
    li= f.text_area 'profile', placeholder: '产品简介'
    li= f.text_field 'title', placeholder: '产品标题'
    li= f.text_field 'price', placeholder: '产品价格'
    li= f.label 'image', value: '图片上传'
    li= f.file_field 'image'
    div
      li= f.submit button_value

app/views/products/edit.html.slim
div= render partial: 'form', locals: {button_value: '更新'}

app/views/products/new.html.slim
div= render partial: 'form', locals: {button_value: '创建'}

app/views/products/show.html.erb
<div class="container">
  <div class="myjumbotron">

    <div class="section content-box container">
      <div class="row">

        <div class="col-md-6">
          <!-- normal -->
    <div class="ih-item square effect3 bottom_to_top"><a>
        <div class="img"><%= image_tag 'left.jpg' %></div>
        <div class="info">
          <h3>产品名称</h3>
         <!-- <p>Description goes here</p> -->
        </div></a></div>
    <!-- end normal -->

        </div>
        <div class="col-md-4 col-md-offset-1">
          <center><h2>产品</h2></center>
          <center><p>标题</p></center>
          <h3>产品介绍 & 描述：</h3>
          <p>dsdsdsdssds</p>
          <h3>产品价格：</h3>
          <p>0 RMB</p>
          <button name="buy" class='btn btn-primary pull-right'> 购买 </button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron">
  <div class="container">
    <center><h2>原材料介绍</h2></center>
    <div class=''>
      <%= image_tag 'test.jpg', class: 'detail' %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="scroll_header_top_area  stick_with_left_right_menu scrolled_not_transparent page_header left_right_margin_set">
 <div class="header_inner clearfix">
  <div class="header_top_bottom_holder">
   <div class="header_bottom clearfix" style="">
    <div class="container">
     <div class="container_inner clearfix">
        <nav class="navbar navbar-default navbar-fixed-top nav-justified">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Brand</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav nav-right">

                <!-- Stack the columns on mobile by making one full-width and the other half-width -->
                <li class="my-li <%= is_active?(0) %>">
                    <a href="/">首页</a>
                </li>
                <li class='my-li <%= is_active?(1) %>'>
                  <a href="/products">产品</a>
                </li>
                <li class="my-li <%= is_active?(2) %>">
                  <a href="/blogs" >博客</a>
                </li>
                <li class="my-li <%= is_active?(3) %>">
                  <a href="/pages/about" >关于GAIA</a>
                </li>
                <li class="my-li <%= is_active?(4) %>">
                  <a href="/pages/contract" >索取样品</a>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
     </div>
    </div>
   </div>
  </div>
 </div>
</header>

app/views/shared/_lunbo.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <!-- <li data-target="#carousel-example-generic" data-slide-to="2"></li> -->
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag 'face-01-24.png' %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag 'face-01-24.png' %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/users/edit.html.slim
div
  = form_for @user do |f|
    li = f.email_field 'email', placeholder: 'email', type: 'email'
    li = f.password_field 'password', placeholder: 'password'
    li = f.text_field 'username', placeholder: 'password'
    li = f.submit '更新信息'

app/views/users/login.html.slim
div
  = form_for @user, url: auth_users_path do |f|
    li = f.email_field 'email', placeholder: 'email', type: 'email'
    li = f.password_field 'password', placeholder: 'password'
    li = f.submit '登陆'

app/views/users/show.html.slim
div
  li= @user.username
  li= @user.email
  li= link_to '编辑用户信息', edit_user_path(hashids(@user.email, @user.id))
  li= link_to '登出', logout_users_path, method: 'delete'